# Generated by Django 5.1.4 on 2025-01-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='img',
            field=models.ImageField(default=0, upload_to='imagenes/'),
            preserve_default=False,
        ),
    ]
