# Generated by Django 5.1.4 on 2025-01-15 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='user.rol'),
        ),
    ]
