# Generated by Django 5.1.4 on 2025-01-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
