# Generated by Django 5.1.4 on 2025-01-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_usuario_rol_delete_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
