# Generated by Django 5.1.4 on 2025-01-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='habilitacion',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
