# Generated by Django 5.1.4 on 2025-01-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_usuario_habilitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntos',
            name='evidencia',
            field=models.ImageField(default=0, upload_to='evidencias/'),
            preserve_default=False,
        ),
    ]
