# Generated by Django 5.1.4 on 2025-01-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_puntos_comentario_subcategoria_puntos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategoria',
            old_name='puntos',
            new_name='puntos_negativos',
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='puntos_positivos',
            field=models.IntegerField(default=0),
        ),
    ]
