# Generated by Django 5.1.4 on 2025-01-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_rename_puntos_subcategoria_puntos_negativos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='total_puntos',
            field=models.IntegerField(default=1000),
        ),
    ]
