# Generated by Django 5.1.4 on 2025-01-27 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_usuario_total_puntos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResumenMensual',
        ),
    ]
